apiVersion: v1
kind: Service
metadata:
  namespace: team-riker
  name: guestbook-ui
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
      app: guestbook-ui
