apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blue-green
  namespace: argocd
spec:
  destinations:
  - namespace: blue-green
    server: https://kubernetes.default.svc
  sourceRepos:
  - git@github.com:nwoodII/argocd-example-apps.git
