apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-green
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: blue-green
  destination:
    namespace: blue-green
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.blueGreen.repoURL }}
    targetRevision: {{ .Values.spec.apps.blueGreen.targetRevision }}
    path: {{ .Values.spec.apps.blueGreen.path }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true